version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Getting Started
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the codes
      - npm run build
      - echo Build finished, now moving to S3
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync out s3://cicd-codebuild-static-website/